blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed
# Create views here

app_name='blog'

urlpatterns = [
	path('', views.post_list, name='post_list'),
	# path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),    
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),   
]

# urlpatterns = [
# 	# post views
# 	url(r'^$', views.post_list, name='post_list'),
# 	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'\
# 	r'(?P<post>[-\w]+)/$',
# 	views.post_detail,
# 	name='post_detail'),
# 	]

blogsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # path(r'^blog/', include('blog.urls',name='blog',app_name='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.


class PublishedManager(models.Manager):
	def get_queryset(self):
		return super(PublishedManager,	self).get_queryset().filter(status='published')


class Post(models.Model):
	STATUS_CHOICES = (
		('draft', 'Draft'),
		('published', 'Published'),
	)
	title = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250,	unique_for_date='publish')
	author = models.ForeignKey(User,related_name='blog_posts', on_delete=models.CASCADE)
	body = models.TextField()
	publish = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=10,choices=STATUS_CHOICES,	default='draft')

	objects = models.Manager() # The default manager.
	published = PublishedManager() # Our custom manager.
	tags = TaggableManager()

	class Meta:
		ordering = ('-publish',)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:post_detail',
					args=[self.publish.year,
					self.publish.strftime('%m'),
					self.publish.strftime('%d'),
					self.slug])


class Comment(models.Model):
		post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
		name = models.CharField(max_length=80)
		email = models.EmailField()
		body = models.TextField()
		created = models.DateTimeField(auto_now_add=True)
		updated = models.DateTimeField(auto_now=True)
		active = models.BooleanField(default=True)
		class Meta:
			ordering = ('created',)
			
		def __str__(self):
			return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment
# Create your forms here

class EmailPostForm(forms.Form):
	name = forms.CharField(max_length=25)
	email = forms.EmailField()
	to = forms.EmailField()
	comments = forms.CharField(required=False,	widget=forms.Textarea)


class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from .models import Post,Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
# Create your views here.


# Function based view
# def post_list(request, tag_slug=None):
# 	posts = Post.published.all()
# 	return render(request,	'blog/post/list.html',	{'posts': posts})


# Class based view
class PostListView(ListView):
	queryset = Post.published.all()
	context_object_name = 'posts'
	paginate_by = 3
	template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
	post = get_object_or_404(Post, slug=post,
							status='published',	
							publish__year=year,	
							publish__month=month,	
							publish__day=day)
	# List of active comments for this post
	comments = post.comments.filter(active=True)
	if request.method == 'POST':
		# A comment was posted
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():
			# Create Comment object but don't save to database yet
			new_comment = comment_form.save(commit=False)
			# Assign the current post to the comment
			new_comment.post = post
			# Save the comment to the database
			new_comment.save()
	else:
		comment_form = CommentForm()

	# List of similar posts
	post_tags_ids = post.tags.values_list('id', flat=True)
	similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
	similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
	context={
	'post': post,
	'comments': comments,
	'comment_form': comment_form,
	'similar_posts': similar_posts,
	}
	return render(request,	'blog/post/detail.html', context)


def post_list(request, tag_slug=None):
	object_list = Post.published.all()
	tag = None
	if tag_slug:
		tag = get_object_or_404(Tag, slug=tag_slug)
		object_list = object_list.filter(tags__in=[tag])
	paginator = Paginator(object_list, 3) # 3 posts in each page
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer deliver the first page
		posts = paginator.page(1)
	except EmptyPage:
		# If page is out of range deliver last page of results
		posts = paginator.page(paginator.num_pages)
	context={
	'page': page,
	'posts': posts,
	'tag': tag
	}

	return render(request, 	'blog/post/list.html', context	)


def post_share(request, post_id):
	# Retrieve post by id
	post = get_object_or_404(Post, id=post_id, status='published')
	sent = False
	if request.method == 'POST':
		# Form was submitted
		form = EmailPostForm(request.POST)
		if form.is_valid():
			# Form fields passed validation
			cd = form.cleaned_data
			# ... send email
			post_url = request.build_absolute_uri(post.get_absolute_url())
			subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
			message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
			send_mail(subject, message, 'admin@myblog.com',	[cd['to']])
			sent = True
	else:
		form = EmailPostForm()
	return render(request, 'blog/post/share.html', {'post': post, 'form': form,'sent': sent})

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">My Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item {% if request.resolver_match.url_name == 'post_list' %}active{% endif %}">
            <a class="nav-link" href="{% url 'blog:post_list' %}">Home</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <main role="main" class="container">
    <div class="row">

    	<!-- Content -->
      <div class="col-md-8">
        {% block content %}
        {% endblock %}
      </div>

      <!-- Side bar -->
      <div class="col-md-4 ">
        <div class="sidebar-module">
	      <h4 class="mt-4">Blog posts</h4>

	      <!-- The number of post submitted so far  -->
	      <p>This is my blog. I've written <strong>{% total_posts %}</strong>  posts so far.</p>

	      	<!-- RSS feed subscription -->
	      	<h4 class="mt-4">Subscribe to RSS</h4>
	     <ul> 
	     	<li> 
	     	<p><a href="{% url 'blog:post_feed' %}">Subscribe to my RSS feed</a></p> 
	     	</li>
	 	</ul>

	      <!-- Latest published posts -->
	      <h4>Latest posts</h4>
			{% show_latest_posts 3 %}

			<!-- The most commented posts -->
			<h4>Most commented posts</h4>
			{% get_most_commented_posts as most_commented_posts %}
			<ul>
				{% for post in most_commented_posts %}
					<li>
						<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
					</li>
				{% endfor %}
			</ul>
        </div>
      </div>
    </div>
  </main>
  <script type="text/javascript" src="{% static 'js/jquery-3.6.4.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

blog/templates/blog/pagination.html
<div class="pagination">
	<span class="step-links">
		{% if page.has_previous %}
			<a href="?page={{ page.previous_page_number }}">Previous</a>
		{% endif %}
		<span class="current">
			Page {{ page.number }} of {{ page.paginator.num_pages }}.
		</span>
		{% if page.has_next %}
			<a href="?page={{ page.next_page_number }}">Next</a>
		{% endif %}
	</span>
</div>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load crispy_forms_tags %} 

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <!-- <div class="container my-5"> -->
    <!-- <div class="row justify-content-center"> -->
      <!-- <div class="col-lg-8"> -->
        <article class="card border-0 shadow-lg rounded-3 my-3 ps-4 pt-2">
          <header class="mb-4">
            <h1>{{ post.title }}</h1>
            <p class="text-muted">{{ post.publish }} by {{ post.author }}</p>
          </header>
          <section class="mb-5">
            <!-- {{ post.body|linebreaks }} -->
            {{ post.body|markdown }}
            <p>
				<a href="{% url 'blog:post_share' post.id %}">
					Share this post
				</a>
			</p>
          </section>
        

          	<!-- Add The Total Comments -->
        {% with comments.count as total_comments %}
			<h4>
				{{ total_comments }} comment{{ total_comments|pluralize }}
			</h4>
		{% endwith %}


			<!-- List Of Comments -->
		{% for comment in comments %}
			<div class="comment ps-1">
				<p class="info">
					Comment {{ forloop.counter }} by {{ comment.name }}
					{{ comment.created }}
				</p>
				{{ comment.body|linebreaks }}
			</div>
		{% empty %}
			<p>There are no comments yet.</p>
		{% endfor %}

		<hr>

			<!-- Adding similar posts -->
		<h2>Similar posts</h2>
		{% for post in similar_posts %}
			<p class="ps-1">
				<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
			</p>
		{% empty %}
			There are no similar posts yet.
		{% endfor %}
			</article>
		<hr>
			<!-- Rendering The Form Or Display A Successful Message -->
		<div class= 'card ps-3 pe-3 border-0 shadow-lg rounded-3'>
		{% if new_comment %}
			<h3>Your comment has been added.</h3>
		{% else %}
			<h3>Add a new comment</h3>
			<form action="." method="post">
				{{ comment_form|crispy}}
				{% csrf_token %}
				<p><input type="submit" value="Add comment"></p>
			</form>
		{% endif %}
		</div>
      <!-- </div> -->
    <!-- </div> -->
  <!-- </div> -->
{% endblock content %}

blog/templates/blog/post/latest_posts.html
<ul>
	{% for post in latest_posts %}
		<li>
			<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
		</li>
	{% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load static %}
{% load crispy_forms_tags %} 

{% block title %}My Blog List{% endblock %}

{% block content %}
  <!-- <div class="container"> -->
    <!-- <div class="row"> -->
      <!-- <div class="col-md-8"> -->
        <h1 class="my-4 ">Blog List</h1>
	        {% if tag %}
	        <h2>Posts tagged with "{{ tag.name }}"</h2>
	        {% endif %}

	        <p class="tags">
		        Tags:
			        {% for tag in post.tags.all %}
				        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
				        	{{ tag.name }}
				        </a>
				        {% if not forloop.last %}, {% endif %}
			        {% endfor %}
	        </p>

        {% for post in posts %}
          <div class="card mb-4 border-0 shadow-lg rounded-3">
            <img class="card-img-top ms-1 mt-1 rounded-circle" src="{% if post.image %}{{ post.image.url }}{% else %}{% static 'img/post-bg.jpg' %}{% endif %}" style="width: 20px; height: 20px;" alt="Post image">
            <div class="card-body">
              <h2 class="card-title">{{ post.title }}</h2>
              <p class="tags"><strong>Tags:</strong>  {{ post.tags.all|join:", " }}</p>
              <!-- <p class="card-text">{{ post.body|truncatewords:30|linebreaks }}</p> -->
              <p class="card-text">{{ post.body|markdown|truncatewords_html:30 }}</p>
              <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
            </div>
            <div class="card-footer text-muted">
              Posted on {{ post.publish }} by {{ post.author }}
            </div>
          </div>
        {% endfor %}
        {% include "blog/pagination.html" with page=posts %}
        <!-- {% include "blog/pagination.html" with page=page_obj %} -->
      <!-- </div> -->
		     <!--  <div class="col-md-4">
		        <div class="card my-4">
		          <h5 class="card-header">About Me</h5>
		          <div class="card-body">
		            <p class="card-text">This is my blog.</p>
		          </div>
		        </div>
		      </div> -->
    <!-- </div> -->
  <!-- </div> -->
{% endblock content %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %} 

{% block title %}Share a post{% endblock %}
{% block content %}
	{% if sent %}
		<h1>E-mail successfully sent</h1>
		<p>
		"{{ post.title }}" was successfully sent to {{ cd.to }}.
		</p>
	{% else %}
		<h1>Share "{{ post.title }}" by e-mail</h1>
		<form action="." method="post">
			{{ form|crispy}}
			{% csrf_token %}
			<input type="submit" value="Send e-mail">
			<!-- <hr>
				rendering each field
			{% for field in form %}
				<div>
					{{ field.errors }}
					{{ field.label_tag }} {{ field }}
				</div>
			{% endfor %}
			 -->
		</form>
	{% endif %}
{% endblock content%}